[BACKLOG-37968] Data Source Wizard - pulldown menus aren't anchored.
pentaho/pentaho-commons-gwt-modules pull request #1012
Opened 2024-01-17 11:32 UTC by varuntangirala

2024-01-17 11:44 UTC, buildguy commented
### :warning: Build finished in 10m 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.gwt.widgets.client.dialogs.PromptDialogBoxTest.testOnOk</b> (click to expand)</summary><p>

```

Wanted but not invoked:
iDialogCallback.okPressed();
-> at org.pentaho.gwt.widgets.client.dialogs.PromptDialogBoxTest.testOnOk(PromptDialogBoxTest.java:74)
Actually, there were zero interactions with this mock.

```

</p></details>

  
Tests run: **345**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-1012/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-01-17 13:32 UTC, buildguy commented
### :warning: Build finished in 10m 31s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.gwt.widgets.client.dialogs.PromptDialogBoxTest.testOnOk</b> (click to expand)</summary><p>

```

Wanted but not invoked:
iDialogCallback.okPressed();
-> at org.pentaho.gwt.widgets.client.dialogs.PromptDialogBoxTest.testOnOk(PromptDialogBoxTest.java:74)
Actually, there were zero interactions with this mock.

```

</p></details>

  
Tests run: **345**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-1012/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-01-17 16:15 UTC, dcleao requested changes
I've met offline with @varuntangirala to ask for some changes on how the timer is managed and limit what is done on the timer event to adjusting the dialog position.

2024-01-18 15:01 UTC, dcleao approved these changes

2024-01-18 15:50 UTC, soagarwal1 approved these changes

2024-01-18 16:08 UTC, merged