[BACKLOG-40086] Schedule Output Perspective : Allow user to browse Scheduled contents from a VFS location folder
pentaho/pentaho-commons-gwt-modules pull request #1028
Opened 2024-03-19 20:35 UTC by singletonc

Issue: https://hv-eng.atlassian.net/browse/BACKLOG-40086
Depends On:

--
- Incorporate new filter parameter into exisiting endpoint calls for Schedule Select Folder Dialog
- Updated applicable "/folders" to "/files" endpoint calls

2024-03-19 20:42 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-03-19 20:42 UTC, buildguy commented
### :white_check_mark: Build finished in 7m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **345**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-1028/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-03-20 20:26 UTC, dcleao requested changes

2024-03-20 20:26 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/folderchooser/FolderTree.java
> +    return getFullyQualifiedURL() + "plugin/scheduler-plugin/api/generic-files/files/";
All good except the `/files` path segment in the URLs, as noted in the related PR.

2024-03-21 23:10 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-03-21 23:11 UTC, buildguy commented
### :white_check_mark: Build finished in 7m 47s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **345**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-1028/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-03-21 23:18 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-03-21 23:18 UTC, buildguy commented
### :white_check_mark: Build finished in 7m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **345**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-1028/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-03-22 11:45 UTC, dcleao approved these changes

2024-03-28 17:18 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-03-28 17:18 UTC, buildguy commented
### :white_check_mark: Build finished in 7m 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **345**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-1028/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-02 13:09 UTC, rmansoor approved these changes

2024-04-02 13:11 UTC, merged