[Backlog 36850] Focus Visible - Accessibility -  PUC Home Page – Manage Data Sources
pentaho/pentaho-commons-gwt-modules pull request #830
Opened 2023-01-30 06:16 UTC by varuntangirala

2023-01-30 06:23 UTC, buildguy commented
### :white_check_mark: Build finished in 6m 17s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **333**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-830/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-01-30 07:48 UTC, buildguy commented
### :white_check_mark: Build finished in 6m 14s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **333**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-830/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-01-30 12:12 UTC, dcleao requested changes

2023-01-30 12:12 UTC, dcleao commented on widgets/src/main/java/org/pentaho/gwt/widgets/client/utils/ElementUtils.java
> + * Copyright (c) 2002-2023 Hitachi Vantara..  All rights reserved.
Please, remove the added, second ".".

2023-01-30 12:12 UTC, dcleao commented on widgets/src/main/resources/org/pentaho/gwt/widgets/themes/public/themes/ruby/globalRuby.css
> +:root {
Should be placed near the beginning of the file (after font stuff).

2023-01-31 12:41 UTC, buildguy commented
### :white_check_mark: Build finished in 5m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **333**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-830/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-02-01 18:24 UTC, dcleao approved these changes

2023-02-01 18:25 UTC, merged