[BACKLOG-37004] Fixed dialogs' title ellipsis not showing
pentaho/pentaho-commons-gwt-modules pull request #856
Opened 2023-02-27 21:13 UTC by dcleao

- For GWT, XUL/GWT and BootstrapJS dialogs

@pentaho/wcag, please, review.

2023-02-27 21:20 UTC, buildguy commented
### :white_check_mark: Build finished in 6m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **378**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-856/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-02-28 11:52 UTC, soagarwal1 approved these changes

2023-02-28 15:14 UTC, NJtwentyone commented on widgets/src/main/resources/org/pentaho/gwt/widgets/themes/public/themes/ruby/globalRuby.css
> +}
no newline at end of file.

2023-02-28 15:14 UTC, NJtwentyone requested changes
minor change: add back newline at end of file

2023-02-28 23:34 UTC, dcleao commented
@NJtwentyone, the change that you mentioned was the new line being added at the end of the file :-)

2023-03-01 00:03 UTC, singletonc approved these changes

2023-03-01 14:47 UTC, NJtwentyone commented on widgets/src/main/resources/org/pentaho/gwt/widgets/themes/public/themes/ruby/globalRuby.css
> +}
mis read the symbol my mistake

2023-03-01 14:47 UTC, NJtwentyone commented
> @NJtwentyone, the change that you mentioned was the new line being added at the end of the file :-)

I miss read the symbol, my mistake.

2023-03-01 14:48 UTC, NJtwentyone approved these changes

2023-03-01 14:48 UTC, merged