[BISERVER-14912] - Creating schedules with “Run Once“ recurrence in Deutsch language does not work in PUC.
pentaho/pentaho-commons-gwt-modules pull request #879
Opened 2023-03-27 17:24 UTC by andreramos89

@smmribeiro 
@bcostahitachivantara 
@renato-s

2023-04-04 09:59 UTC, smmribeiro requested changes

2023-04-04 09:59 UTC, smmribeiro commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/validators/RunOnceEditorValidator.java
> +      return dateString.replaceAll( "vorm." , "am").replaceAll( "nachm." , "pm") ;
Also, I'm very curious: is it only in german that one gets words different from AM/PM?

2023-05-05 12:01 UTC, buildguy commented
### :white_check_mark: Build finished in 6m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **330**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-879/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-05-08 14:39 UTC, dcleao requested changes

2023-05-08 14:39 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/validators/RunOnceEditorValidator.java
> +  }
Formatting is off.

2023-05-08 14:40 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/validators/RunOnceEditorValidator.java
> +  }
Also, this implementation looks to be, essentially, a hack. Could a locale-aware date function be used instead?

2023-05-19 09:38 UTC, buildguy commented
### :white_check_mark: Build finished in 9m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **398**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-879/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-05-22 11:19 UTC, dcleao requested changes
Also, formatting is off.

2023-05-22 11:19 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/validators/RunOnceEditorValidator.java
> +        }
Test for presence of AM/PM is already done inside `normalizeTime`. There's no need to repeat, afaict.

2023-05-22 11:19 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/validators/RunOnceEditorValidator.java
> +      String time = editor.getStartTime();  //format of time is "hh:mm:ss a"
Variable can be moved to inside the below `else` case.

2023-05-22 11:19 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/validators/RunOnceEditorValidator.java
> +    return time;
IMO, would be simpler if the AM/PM tests would only be done by the inner `if`/`else`, while transforming the `else` into an `else if` for PM.

2023-05-25 09:43 UTC, buildguy commented
### :white_check_mark: Build finished in 7m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **398**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-879/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-05-25 11:33 UTC, buildguy commented
### :white_check_mark: Build finished in 7m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **398**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-879/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-05-25 11:54 UTC, dcleao approved these changes

2023-05-31 22:30 UTC, smmribeiro approved these changes

2023-05-31 22:30 UTC, merged