[BACKLOG-37783] Added keyboard Navigation and focus visibility for  top part of Sidebar and in Formatting panel-> tabs for color palette
pentaho/pentaho-commons-gwt-modules pull request #937
Opened 2023-06-01 15:10 UTC by kdarshana12

Made close button for color palette and query-options button keyboard accessible 
@pentaho/wcag , please review

2023-06-01 15:16 UTC, buildguy commented
### :white_check_mark: Build finished in 6m 13s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **428**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-937/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-06-01 15:21 UTC, dcleao requested changes

2023-06-01 15:21 UTC, dcleao commented on widgets/src/main/resources/org/pentaho/gwt/widgets/themes/public/themes/ruby/globalRuby.css
>    background: url('images/closeTab_active.png')no-repeat top left;
Also, please add a space before `no-repeat`.

2023-06-05 06:29 UTC, phalguni-a approved these changes

2023-06-05 06:59 UTC, merged