[BACKLOG-37742] Page Zoom (AA) - Data Source Wizard Dialog-Database tables subsequent dialogs
pentaho/pentaho-commons-gwt-modules pull request #939
Opened 2023-06-13 08:22 UTC by varuntangirala

@pentaho/wcag Please review

2023-06-14 13:10 UTC, dcleao requested changes

2023-06-14 13:10 UTC, dcleao commented on widgets/src/main/resources/org/pentaho/gwt/widgets/themes/public/themes/ruby/globalRuby.css
> +  }
This rule should be together with other rules of the same dialog. Unfortunately, that means repeating the media query statement in other places.

2023-06-15 08:06 UTC, varuntangirala commented on widgets/src/main/resources/org/pentaho/gwt/widgets/themes/public/themes/ruby/globalRuby.css
> +  min-height: 7em;
All the list boxes in the database tables and SQL file type needs an some min-height. So previously we used 7em for #connectionList and 6em for #query id which have been removed below in the current PR. Also there are 5 more list boxes(ids: #availableTables, #selectedTables, #leftTables, #rightTables, #joins in main_wizard_panel.xul) which needs an min-height.

2023-06-15 11:32 UTC, dcleao commented on widgets/src/main/resources/org/pentaho/gwt/widgets/themes/public/themes/ruby/globalRuby.css
> +  min-height: 7em;
So, approximately, how many list items fit in `7em`?

I believe it is something like:
7em * font-size of 14px / ( measured-line-height of 19px - row-gap of 2px ) ~= 4.5 items

Maybe 3.5 items would be more appropriate as a general default.
3.5 * (19 + 2) / 14 = 5.25em;

Either way, please add a comment above the property mentioning how many line items are expected.

2023-06-15 11:37 UTC, dcleao commented on widgets/src/main/resources/org/pentaho/gwt/widgets/themes/public/themes/ruby/globalRuby.css
> +}
In the "Open File" dialog, the location listbox, in dropdown mode, when with a very long text, wraps into multiple lines. Was that changed in this PR somehow?
If not, what is causing this listbox to behave differently and overflow?

2023-06-15 12:27 UTC, buildguy commented
### :white_check_mark: Build finished in 6m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **428**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-939/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-06-16 15:53 UTC, buildguy commented
### :white_check_mark: Build finished in 6m
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **428**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-939/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-06-16 17:23 UTC, dcleao approved these changes

2023-06-19 08:03 UTC, merged