[BACKLOG-36861] - Page Zoom (AA) - Manage Data Source Dialog
pentaho/pentaho-commons-gwt-modules pull request #941
Opened 2023-06-16 07:42 UTC by soagarwal1

@pentaho/wcag Please Review

2023-06-16 07:48 UTC, buildguy commented
### :warning: Build finished in 6m 16s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.gwt.widgets.client.table.BaseTableTest.testShowMessage</b> (click to expand)</summary><p>

```

Argument(s) are different! Wanted:
baseTable.createTable(
    <any>,
    <any>,
    <any>,
    FIXED_WIDTH,
    <any>
);
-> at org.pentaho.gwt.widgets.client.table.BaseTableTest.testShowMessage(BaseTableTest.java:73)
Actual invocation has different arguments:
baseTable.createTable(
    ["&nbsp;"],
    null,
    [[Ljava.lang.String;@6060f163],
    FILL_WIDTH,
    null
);
-> at org.pentaho.gwt.widgets.client.table.BaseTableTest.testShowMessage(BaseTableTest.java:70)

```

</p></details>

  
Tests run: **428**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-941/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-06-16 08:05 UTC, buildguy commented
### :white_check_mark: Build finished in 6m 7s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **428**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-941/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-06-16 17:34 UTC, dcleao requested changes

2023-06-19 08:06 UTC, soagarwal1 commented on widgets/src/main/java/org/pentaho/gwt/widgets/client/utils/ElementUtils.java
> +  }-*/;
Done

2023-06-19 08:12 UTC, buildguy commented
### :white_check_mark: Build finished in 6m
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **428**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-941/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-06-19 13:33 UTC, varuntangirala approved these changes

2023-06-19 13:46 UTC, buildguy commented
### :white_check_mark: Build finished in 5m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **428**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-941/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-06-19 13:59 UTC, merged