[BACKLOG-37966] Toolbar improvements in PUC
pentaho/pentaho-commons-gwt-modules pull request #960
Opened 2023-09-04 12:01 UTC by AAravind27

@pentaho/wcag , Please review for https://hv-eng.atlassian.net/browse/BACKLOG-37966

2023-09-07 12:31 UTC, dcleao requested changes

2023-09-08 08:45 UTC, AAravind27 commented on widgets/src/main/java/org/pentaho/gwt/widgets/client/toolbar/Toolbar.java
> +      public void onBrowserEvent( Event event ) {
It works. thankyou

2023-09-08 17:21 UTC, dcleao approved these changes

2023-09-11 18:04 UTC, hv-vamsi approved these changes

2023-09-12 04:59 UTC, merged