[BACKLOG-38136] PUC UI Changes
pentaho/pentaho-commons-gwt-modules pull request #964
Opened 2023-09-07 04:05 UTC by srallapa

2023-09-07 16:52 UTC, ddiroma commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/AdditionalDetailsPanel.java
> +package org.pentaho.mantle.client.dialogs.scheduling;
@srallapa Please add copyright header

2023-09-07 16:53 UTC, ddiroma commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/AdditionalDetailsPanel.java
> +import com.google.gwt.user.client.ui.*;
@srallapa Please use specific import instead of .*

2023-09-07 16:56 UTC, ddiroma commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/AdditionalDetailsPanel.java
> +import org.pentaho.gwt.widgets.client.controls.ErrorLabel;
You have some checkstyle issues. Please run our checkstyle in Intellij using these instructions:
the README.md file in https://github.com/pentaho/pentaho-coding-standards

2023-09-07 16:58 UTC, ddiroma commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/RunOnceEditor.java
> +import com.google.gwt.user.client.ui.*;
@srallapa Please use specific import instead of .*

2023-09-07 16:58 UTC, ddiroma commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleRecurrenceDialog.java
> +import java.util.*;
@srallapa Please use specific import instead of .*

2023-09-08 04:06 UTC, buildguy commented
### :white_check_mark: Build finished in 15m 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **423**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-964/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-09-08 16:53 UTC, dcleao requested changes

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/AdditionalDetailsPanel.java
> + * Copyright (c) 2023-2024 Hitachi Vantara..  All rights reserved.
It isn't 2024 yet. Should be 2023 alone.

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/AdditionalDetailsPanel.java
> +    private static final String SCHEDULER_ADDITIONAL_PANEL = "schedule-editor-additional-panel"; //$NON-NLS-1$
These `//$NON-NLS-1$` are remnants from the past and not needed anymore afaik.

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/AdditionalDetailsPanel.java
> +        HorizontalFlexPanel logLvlHP = new HorizontalFlexPanel();
Unless there's a need to make these names shorter, it would be easier to read if named `logLevelHP`.

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/AdditionalDetailsPanel.java
> +        Label l = new Label( Messages.getString( "schedule.logLevel" ) );
Please, use a bigger name for the variable.

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/AdditionalDetailsPanel.java
> +        VerticalFlexPanel dVP = new VerticalFlexPanel();
It is not clear what this variable name stands for. Please, give it a clearer name.

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/AdditionalDetailsPanel.java
> +        detailVP.add( detailsLabel );
Please, be consistent in naming. Unless there is some reason, these should all either use the `details` or the `detail` prefix (I believe the former is more common).

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/AdditionalDetailsPanel.java
> +    private CheckBox gatherMetrics;
Formatting still does not seem to follow the Pentaho coding standards — indentation is using 4 spaces, instead of 2.

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/RecurrenceEditor.java
> +  public String getLogLevelLb() {
Why is `Lb`, presumably a suffix for "Listbox", relevant in this property name? Seems like a private detail.

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/RunOnceEditor.java
> +  public String getLogLevelLb() {
Same comment regarding `Lb` suffix on `RecurrenceEditor` applies.

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditor.java
> +  public void setLogLevelLb( String logLevelLb ) {
Same comment regarding `Lb` suffix on `RecurrenceEditor` applies.

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditor.java
> +  public String getLogLevelLb() {
Same comment regarding `Lb` suffix on `RecurrenceEditor` applies.

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditor.java
> +        throw new RuntimeException( Messages.getString( "schedule.invalidRunType", getScheduleType().toString() ) );
The used error string does not seem to apply: `schedule.invalidRunType`.

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleEditorWizardPanel.java
> +  public String getLogLevelLb() {
Same comment regarding `Lb` suffix on `RecurrenceEditor` applies.

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/ScheduleRecurrenceDialog.java
> +      for ( int i = 0; i < jsJob.getJobParams().length(); i++ ) {
Please, add empty line after previous block.

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/workspace/JsJobTrigger.java
> +  public final native String getLogLevelLb() /*-{ return this.logLevelLb; }-*/;
Same comment regarding `Lb` suffix on `RecurrenceEditor` applies.

2023-09-08 16:53 UTC, dcleao commented on widgets/src/main/java/org/pentaho/gwt/widgets/client/utils/TimeUtil.java
> +   */
Does this comment also apply to this enum? Could not find any new resource bundle strings with these names.

Is there an unlinked associated PR?

2023-09-08 16:58 UTC, dcleao commented on widgets/src/main/java/org/pentaho/gwt/widgets/client/utils/TimeUtil.java
> +   */
It looks like there is one: https://github.com/pentaho/pentaho-platform/pull/5380.

Ideally, please link associated PRs to each other (or have one of the PRs be the head of a set, that links to the other PRs).

Still, the first statement applies.

2023-09-08 17:27 UTC, dcleao requested changes

2023-09-08 17:27 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/AdditionalDetailsPanel.java
> +        for ( int ii = 0; ii < TimeUtil.LogLevel.length(); ++ii ) {
Please, use either a single letter variable, such as the common `i`, or a more descriptive name such as `index`.

2023-09-08 17:27 UTC, dcleao commented on widgets/src/main/java/org/pentaho/mantle/client/dialogs/scheduling/AdditionalDetailsPanel.java
> +        for ( int ii = 0; ii < TimeUtil.LogLevel.length(); ++ii ) {
Please, use either a single letter variable, such as the common `i`, or a more descriptive name such as `index`.

2023-09-08 21:52 UTC, buildguy commented
### :warning: Build finished in 14m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 3 test(s) failed:

<details><summary><b>org.pentaho.gwt.widgets.client.utils.TimeUtilTest.testGetNextLogTest</b> (click to expand)</summary><p>

```
expected:<2> but was:<3>
```

</p></details>

<details><summary><b>org.pentaho.mantle.client.dialogs.scheduling.AdditionalDetailsPanelTest.testGetLogLevel</b> (click to expand)</summary><p>

```
expected:<Basic> but was:<null>
```

</p></details>

<details><summary><b>org.pentaho.mantle.client.dialogs.scheduling.AdditionalDetailsPanelTest.testGetEnableSafeMode</b> (click to expand)</summary><p>

```
expected:<true> but was:<false>
```

</p></details>

  
Tests run: **432**, Failures: **3**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-964/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-09-08 22:06 UTC, buildguy commented
### :warning: Build finished in 14m 21s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 3 test(s) failed:

<details><summary><b>org.pentaho.gwt.widgets.client.utils.TimeUtilTest.testGetNextLogTest</b> (click to expand)</summary><p>

```
expected:<2> but was:<3>
```

</p></details>

<details><summary><b>org.pentaho.mantle.client.dialogs.scheduling.AdditionalDetailsPanelTest.testGetLogLevel</b> (click to expand)</summary><p>

```
expected:<Basic> but was:<null>
```

</p></details>

<details><summary><b>org.pentaho.mantle.client.dialogs.scheduling.AdditionalDetailsPanelTest.testGetEnableSafeMode</b> (click to expand)</summary><p>

```
expected:<true> but was:<false>
```

</p></details>

  
Tests run: **432**, Failures: **3**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-964/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-09-09 20:22 UTC, buildguy commented
### :warning: Build finished in 16m 23s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.mantle.client.dialogs.scheduling.AdditionalDetailsPanelTest.testGetLogLevel</b> (click to expand)</summary><p>

```
expected:<Basic> but was:<null>
```

</p></details>

<details><summary><b>org.pentaho.mantle.client.dialogs.scheduling.AdditionalDetailsPanelTest.testGetEnableSafeMode</b> (click to expand)</summary><p>

```
expected:<true> but was:<false>
```

</p></details>

  
Tests run: **432**, Failures: **2**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-964/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-09-11 14:43 UTC, dcleao approved these changes

2023-09-11 19:13 UTC, buildguy commented
### :warning: Build finished in 15m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.mantle.client.dialogs.scheduling.AdditionalDetailsPanelTest.testGetLogLevel</b> (click to expand)</summary><p>

```

Wanted but not invoked:
listBox.setSelectedIndex(3);
-> at org.pentaho.mantle.client.dialogs.scheduling.AdditionalDetailsPanelTest.testGetLogLevel(AdditionalDetailsPanelTest.java:49)
Actually, there were zero interactions with this mock.

```

</p></details>

  
Tests run: **432**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-964/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-09-11 19:28 UTC, buildguy commented
### :warning: Build finished in 14m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.mantle.client.dialogs.scheduling.AdditionalDetailsPanelTest.testGetLogLevel</b> (click to expand)</summary><p>

```

Wanted but not invoked:
listBox.setSelectedIndex(3);
-> at org.pentaho.mantle.client.dialogs.scheduling.AdditionalDetailsPanelTest.testGetLogLevel(AdditionalDetailsPanelTest.java:49)
Actually, there were zero interactions with this mock.

```

</p></details>

  
Tests run: **432**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-964/8/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-09-11 19:43 UTC, buildguy commented
### :white_check_mark: Build finished in 14m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **431**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-964/9/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-09-11 20:51 UTC, peterrinehart approved these changes

2023-09-11 20:52 UTC, merged