[BACKLOG-38706] WCAG - PIR - Page Zoom: Filter Dialog
pentaho/pentaho-commons-gwt-modules pull request #994
Opened 2023-11-21 13:24 UTC by jsaraf

Please review @pentaho/wcag 
To be merged alongside https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1723

2023-11-21 13:39 UTC, buildguy commented
### :white_check_mark: Build finished in 14m 25s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **436**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-994/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-11-21 15:18 UTC, dcleao requested changes
Based on @mbrasil's concerns, that FilterDialog.css was only being included in PIR.html, some of these selectors may be too wide for a global context. So, I ask you to prefix the rules with `:where(.filter-dialog)`

2023-11-22 10:51 UTC, dcleao approved these changes

2023-11-22 13:59 UTC, hv-vamsi approved these changes

2023-11-23 06:19 UTC, merged