Addresses BACKLOG-37996: WCAG main page zoom
pentaho/pentaho-commons-gwt-modules pull request #998
Opened 2023-12-05 18:22 UTC by mbrasil

@pentaho/wcag and @pentaho/millenniumfalcon please review

2023-12-05 18:34 UTC, buildguy commented
### :white_check_mark: Build finished in 12m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **436**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-998/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-12-07 11:17 UTC, davidmsantos90 requested changes

2023-12-07 11:17 UTC, davidmsantos90 commented on widgets/src/main/resources/org/pentaho/gwt/widgets/themes/public/themes/ruby/globalRuby.css
> +
similar to what was done with other icon styles, at least the `vars` and `height/width` could be aggregated in one selector. eg: `.tundra :is(.dijitEditorIcon.dijitEditorIconUndo, ..., ...) {`

also take a look at the following icon styles (bellow), there is a lot of repetition that can be avoided if we aggregate them 💪🏼

2023-12-07 17:47 UTC, mbrasil commented on widgets/src/main/resources/org/pentaho/gwt/widgets/themes/public/themes/ruby/globalRuby.css
> +  background-image: url('images/16x16_left.png');
You're right, but I had this covered. There is a class called `sidePanelIconCommon` that has all things common between `sidePanelIconOpen` and `sidePanelIconClose` and it's in there.

2023-12-07 18:41 UTC, buildguy commented
### :white_check_mark: Build finished in 12m 38s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **436**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-998/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-12-07 18:53 UTC, buildguy commented
### :white_check_mark: Build finished in 12m 24s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **436**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-998/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-12-11 15:27 UTC, davidmsantos90 approved these changes

2023-12-14 13:14 UTC, buildguy commented
### :white_check_mark: Build finished in 12m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl widgets
```
---
:ok_hand: All tests passed!
 
Tests run: **436**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/gwt-widgets/job/PR-998/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-12-14 14:33 UTC, dcleao approved these changes

2023-12-14 14:35 UTC, merged